add support for LIMIT&SLIMIT
thulab/iotdb-jdbc pull request #52
Opened 2018-03-20 04:37 UTC by LeiRui

2018-03-20 04:46 UTC, LeiRui commented
[Tower](https://tower.im/projects/36de8571a0ff4833ae9d7f1c5c400c22/todos/bf7e242ce49d42bf83063cbc8461147d/)

2018-03-21 03:26 UTC, MyXOF requested changes
next方法的逻辑需要给我讲下，光看没太看明白

2018-03-21 03:26 UTC, MyXOF commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +        int posLimit = Arrays.asList(splited).indexOf("LIMIT");
像"LIMIT"，"OFFSET"这样特殊的关键字建议用一个final成员变量来保存，不建议直接写在代码逻辑里面

2018-03-21 03:26 UTC, MyXOF commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +            }
这里还需不需要有一个else来处理其他的情况

2018-03-21 03:26 UTC, MyXOF commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +			return false;
这部分代码格式有点乱，格式化一下吧

2018-03-21 08:45 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +			return false;
modified

2018-03-21 08:46 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +            }
No. If the code runs here, then leave 'seriesLimit' as it is.

2018-03-21 08:46 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +        int posLimit = Arrays.asList(splited).indexOf("LIMIT");
modified

2018-03-21 11:35 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
>  public class TsfileQueryResultSet implements ResultSet {
这个类的代码可以一键格式化一下。

2018-03-21 11:44 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +            int posOffset = Arrays.asList(splited).indexOf(OFFSET_STR);
Arrays.asList(splited) 这个做一次转化就行吧，同下面

2018-03-21 11:49 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +		if(seriesLimit == -1) { // if slimit is unset
limit < -1的数值不会走到这几步是吧

2018-03-21 11:58 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +			if(seriesOffset==-1) { // if soffset is unset
感觉这两个if判断条件可以合成一个

2018-03-21 11:58 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +                // assign 0 to seriesLimit so next() will return 'false' instantly without needing to fetch data
感觉注释语句加在赋值语句前面比较好些？

2018-03-21 11:58 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +		int tmpEnd = seriesOffset+seriesLimit;
感觉tmpEnd还是换个命名是不是更规范些哈？

2018-03-21 11:58 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +	public boolean nextWithoutLimit() throws SQLException{
函数可为private

2018-03-21 12:21 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +                        return false;// cannot move to the next record position where OFFSET indicates
这个循环里一直读数据不需要rowsCount++吗

2018-03-21 12:21 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +				rowsCount++;
这个if(rowsLimit!=-1)判断里处理的逻辑能不能直接拿到上面那个if(rowsLimit!=-1)的判断里

2018-03-21 12:21 UTC, Beyyes commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +		if(!nextWithoutLimit()){
rowsLimit!=-1时直接返回!nextWithoutLimit()怎么样

2018-03-21 15:09 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +		if(seriesLimit == -1) { // if slimit is unset
limit在这个类中初始化-1有一定的状态标识作用。如果sql中没有LIMIT语句，limit就仍然是初始值-1，如果sql中有LIMIT语句，那么由于这里的sql已经通过了语法检查，所以LIMIT参数一定是非负整数。OFFSET同理。
这里是想note一下（LIMIT&OFFSET）和（SLIMIT&SOFFSET）两组参数的处理方式有所不同，后一组参数在从sql中解析之后还有额外的修改。

2018-03-21 15:11 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +                        return false;// cannot move to the next record position where OFFSET indicates
不需要，因为这一段的作用是先把读取位移到rowsOffset，这一段是一个一次性的代码，执行过一次之后就不再执行了。

2018-03-21 15:27 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +				rowsCount++;
不太好拿，上面那段里还没有真正意义上取下一条

2018-03-21 15:37 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +		if(!nextWithoutLimit()){
是不是改成：
boolean isNext=nextWithoutLimit();
if(isNext && rowsLimit !=-1) {
    rowsCount++;
}
return isNext;

目前是：
if (!nextWithoutLimit()) {
     return false;
} else {
     if (rowsLimit != -1) {
          rowsCount++;
     }
     return true;
}

但我不知道是否第一种逻辑比第二种更清晰？改成第一种会更好？

2018-03-21 15:38 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +	public boolean nextWithoutLimit() throws SQLException{
好的

2018-03-21 15:38 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +                // assign 0 to seriesLimit so next() will return 'false' instantly without needing to fetch data
好的

2018-03-21 15:38 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +			if(seriesOffset==-1) { // if soffset is unset
好的

2018-03-21 15:38 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +            int posOffset = Arrays.asList(splited).indexOf(OFFSET_STR);
好的

2018-03-21 15:38 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
>  public class TsfileQueryResultSet implements ResultSet {
OK

2018-03-22 07:31 UTC, jt2594838 commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +            rowsLimit = Integer.parseInt(splited[posLimit + 1]);
这里是否需要try-catch一下。我看在antlr虽然有格式解析，但是没有限制长度，如果输入一个长度超过int32的数这里会抛出异常吧。

2018-03-23 04:23 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +            rowsLimit = Integer.parseInt(splited[posLimit + 1]);
是的，功能设计文档中是UINT32，确实可以在这里检查一下长度。

2018-03-23 10:59 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +            rowsLimit = Integer.parseInt(splited[posLimit + 1]);
已改，谢谢

2018-03-27 02:25 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +		if(!nextWithoutLimit()){
两种功能上没有区别，已改成第一种，因为第一种看上去比较好理解

2018-04-09 02:17 UTC, MyXOF approved these changes

2018-04-09 02:17 UTC, merged