Metadata organizing
thulab/iotdb-jdbc pull request #59
Opened 2018-07-25 11:09 UTC by LeiRui

&Tower："show timeseries客户端挂掉"：《metadata修改开发文档》

2018-08-23 03:27 UTC, jixuan1989 requested changes

2018-08-23 03:27 UTC, jixuan1989 commented on src/test/java/cn/edu/tsinghua/iotdb/jdbc/MetadataTest.java
> +    public static void main(String[] args) throws ClassNotFoundException, SQLException {
得用UT框架来写。。这种main的形式，不能被自动UT框架运行。

有两种手段：
1. 使用MockitoAnnotations
2. Before()函数中，自动启动一个IoTDB，然后导入一些数据，然后开始测试。after()函数中关闭iotdb，删除数据。

2018-08-24 04:11 UTC, MyXOF commented on pom.xml
> +			<version>0.7.0</version>
不建议这么做，这样会造成jdbc和iotdb互相引用的状态，最好是1）使用mock，2）在实验室的集群装一个iotdb，每次连这个测，3）使用docker

2018-10-10 07:46 UTC, MyXOF requested changes
把一些小问题改改就可以了过了

2018-10-10 07:46 UTC, MyXOF commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileJDBCConfig.java
> +	public static int metaDataBatchFetchSize = 10000;
这个设了默认值，别的地方能修改吗？

2018-10-10 07:46 UTC, MyXOF commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileDatabaseMetadata.java
> +            		System.out.println(e);
输出？

2018-10-10 07:46 UTC, MyXOF commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileMetadataResultMetadata.java
> +   This class is designed for TsfileMetadataResultSet to be used in a similar way to TsfileQueryResultSet, for example:
不用这么表达的这么复杂吧，
TsfileMetadataResultSet implements a similar api like TsfileQueryResultSet to display colum metadata

2018-10-10 07:46 UTC, MyXOF commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileMetadataResultSet.java
> +import org.apache.thrift.TException;
这些引用石多余的吧

2018-10-10 14:44 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileJDBCConfig.java
> +	public static int metaDataBatchFetchSize = 10000;
无用默认值，删掉。
这个默认值本来是用于show timeseries <path>结果的分批查询的，后来这个分批方法不成熟被换掉，因此此处这个属性值在本次pr中也就没有用处了。

2018-10-10 14:49 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileMetadataResultMetadata.java
> +   This class is designed for TsfileMetadataResultSet to be used in a similar way to TsfileQueryResultSet, for example:
已改

2018-10-10 14:50 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileMetadataResultSet.java
> +import org.apache.thrift.TException;
已删除

2018-10-10 14:56 UTC, LeiRui commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileDatabaseMetadata.java
> +            		System.out.println(e);
是的 在这个重载函数里没有抛出这个异常 而是直接打印这个异常了

2018-10-10 15:05 UTC, LeiRui commented
修改完成，等待下一次review。

2018-10-11 03:45 UTC, LeiRui commented
修改完成，等待下一次review。

2018-10-12 02:06 UTC, MyXOF commented
和现在的master分支有冲突，麻烦解决下。另外把pom和readme文件的应用换成0.8.0-SNAPSHOT

2018-10-12 14:17 UTC, LeiRui commented
修改完成，等待下一次review。

2018-10-15 06:56 UTC, MyXOF approved these changes

2018-10-17 00:58 UTC, jixuan1989 approved these changes

2018-10-17 01:00 UTC, jixuan1989 commented
合并之后，请和馨怡沟通，将用户手册更新。

@stefaniexin 
是否考虑将用户手册从doc版本变成在线版，方便大家一起更新？(但是如何确保用户手册中的内容都正确）

2018-10-17 05:57 UTC, merged