Iotdb read refactor
thulab/iotdb-jdbc pull request #61
Opened 2018-09-04 12:51 UTC by qiaojialin

2018-09-05 07:21 UTC, jt2594838 requested changes

2018-09-05 07:21 UTC, jt2594838 commented on interface/rpc.thrift
> +}
这样的设计是不是过于沉重了，为了仅仅保存一个点，需要使用4 + 4 + 4 + 8 + 8 + 8 + 8 + 8 = 52个字节。

2018-09-05 07:21 UTC, jt2594838 commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/TsfileQueryResultSet.java
> +		return null;
为什么不把columnName拓展成path，再用path直接从map取值？

2018-09-05 07:21 UTC, jt2594838 commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/Utils.java
> +						r.getFields().put(path, new TsPrimitiveType.TsBoolean(value.isBool_val()));
为什么是isBool_val()？
话说这个混合下划线和驼峰的神奇命名方式是什么鬼。

2018-09-05 07:21 UTC, jt2594838 commented on src/test/java/cn/edu/tsinghua/iotdb/jdbc/JDBCTest.java
> +				System.out.println(builder);
print一下就完了？不做任何正确性验证吗？
另外要写测试的话就写到测试框架里吧，不然没有太大的意义。

2018-09-05 09:08 UTC, qiaojialin commented on interface/rpc.thrift
> +}
这不是optional吗，实际存的时候应该只会选择一个吧

2018-09-05 09:27 UTC, jt2594838 commented on interface/rpc.thrift
> +}
optional是指序列化到外存的时候不一定序列化，但是内存占用不会减少把。

2018-09-05 10:06 UTC, qiaojialin commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/Utils.java
> +						r.getFields().put(path, new TsPrimitiveType.TsBoolean(value.isBool_val()));
thrift应该是要去掉的，不影响正确性先合了吧

2018-09-06 06:09 UTC, jt2594838 commented on src/main/java/cn/edu/tsinghua/iotdb/jdbc/Utils.java
> +						r.getFields().put(path, new TsPrimitiveType.TsBoolean(value.isBool_val()));
行吧

2018-09-12 07:15 UTC, jt2594838 approved these changes

2018-09-12 07:15 UTC, jt2594838 commented on interface/rpc.thrift
> +}
已记为一个issue

2018-09-12 07:15 UTC, merged